version: '3.8'

services:
  nextjs-app:
    build: .
    container_name: nextjs-container
    restart: always
    ports:
      - "6000:4000"  # Map container port to host port
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api/
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
