version: '3.8'

services:
  nextjs-app:
    build: .
    container_name: nextjs-container
    restart: always
    ports:
      - "3000:3000"  # Map container port to host port
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api/
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
