version: '3.8'

services:
  node-app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST: postgres-db-new
      DB_USER: admin
      DB_PASSWORD: adminpassword
      DB_NAME: my_database
      PORT : 5000
      DB_PORT: 5432
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    external: true  # Connect to the same custom network
