name: DB CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'Db/**'

jobs:
  build-db:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & Create Package
        id: build-docker-image
        uses: ./.github/actions/package-generation
        with:
          folder: 'db'
          tagname: 'database'
          token: ${{ secrets.GITHUB_TOKEN }}  



