name: Frontend CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'FE/**'

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & Create Package
        id: build-docker-image
        uses: ./.github/actions/package-generation
        with:
          folder: 'FE'
          tagname: 'frontend'
          token: ${{ secrets.GITHUB_TOKEN }}  # Pass the token here
