name: Frontend CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'FE/**'

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and tag Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}-frontend:${IMAGE_TAG} .
          docker tag ghcr.io/${{ github.repository }}-frontend:${IMAGE_TAG} ghcr.io/${{ github.repository }}-frontend:latest

      - name: Push Docker images to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}-frontend:${IMAGE_TAG}
          docker push ghcr.io/${{ github.repository }}-frontend:latest