name: Deploy Frontend to EC2

on:
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<YOUR_EC2_PUBLIC_IP> << 'EOF'

            echo "Logging into GHCR"
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            echo "Pulling latest image"
            docker pull ghcr.io/${{ github.repository }}-frontend:latest

            echo "Stopping old container (if exists)"
            docker rm -f frontend-container || true

            echo "Running new container"
            docker run -d \
              --name frontend-container \
              -p 3000:3000 \
              ghcr.io/${{ github.repository }}-frontend:latest

          EOF
