name: Deploy Frontend from ECR to EC2

on:
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user                # or ubuntu for Ubuntu AMIs
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |

            aws ecr get-login-password --region us-east-2 | \
              docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com

            # Stop and remove existing container on port 80 (optional)
            # docker ps -q --filter "name=frontend" | grep -q . && docker stop $(docker ps -q --filter "name=frontend") || echo "No container on port 80"
            # docker ps -a -q --filter "name=frontend" | grep -q . && docker rm $(docker ps -a -q --filter "name=frontend") || echo "No stopped container on port 80"

            docker stop frontend

            docker rm frontend

            # Remove all unused containers
            docker container prune -f

            # Remove all the unused images
            docker image prune -a -f

            # Pull the latest image
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/${{secrets.AWS_ECR_REPO}}:latest

            # Run the container on port 80
            docker run -d -p 80:3000 \
              --name frontend \
              -e NEXT_PUBLIC_API_URL=${{ secrets.EC2_PUBLIC_HOST }} \
              -e PORT=3000 \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com/${{secrets.AWS_ECR_REPO}}:latest
